011 crud parameters
blc132/iPetCare.API pull request #11
Opened 2020-03-29 17:18 UTC by jpisarek

2020-03-29 20:36 UTC, kobrynsky requested changes

2020-03-29 20:36 UTC, kobrynsky commented on iPetCare/Application/Services/ExaminationParameterService.cs
> +            if (CurrentlyLoggedUser == null)
to lepiej przerzucić na górę (tak samo jak sprawdzanie czy user jest adminem).

2020-03-29 20:36 UTC, kobrynsky commented on iPetCare/Application/Services/ExaminationParameterService.cs
> +            var examinationParameter = new ExaminationParameter()
do tego mozemy wykorzystac mappera

2020-03-29 20:36 UTC, kobrynsky commented on iPetCare/Application/Services/ExaminationParameterService.cs
> +            var responseDto = new ExaminationParametersCreateExaminationParameterDtoResponse()
tutaj też mozesz uzyć mappera

2020-03-29 20:36 UTC, kobrynsky commented on iPetCare/Application/Services/ExaminationParameterService.cs
> +                return new ServiceResponse<ExaminationParametersUpdateExaminationParameterDtoResponse>(HttpStatusCode.BadRequest, "Nie ma takiego parametru");
tutaj notfound powinno być

2020-03-29 20:36 UTC, kobrynsky commented on iPetCare/Application/Services/ExaminationParameterService.cs
> +                return new ServiceResponse<ExaminationParametersUpdateExaminationParameterDtoResponse>(HttpStatusCode.BadRequest, "Nie ma takiego badania");
tutaj też notfound

2020-03-29 20:36 UTC, blc132 commented on iPetCare/Application/Services/ExaminationParameterService.cs
> +            if ((await Context.ExaminationParameters.Where(x => x.Name == dto.Name && x.ExaminationTypeId == dto.ExaminationTypeId).AnyAsync()) && result == 0)
poprawić tak jak rozmawialiśmy xD

2020-03-29 20:36 UTC, blc132 commented on iPetCare/API/Controllers/ExaminationTypesController.cs
> +        [HttpGet("examinationtype/{examinationTypeId}")]
tutaj url z geta ktory będzie usunięty

2020-03-30 23:27 UTC, kobrynsky submitted a review, later dismissed

2020-03-31 10:41 UTC, JJMPdsk commented on iPetCare/Application/Dtos/ExaminationParameters/ExaminationParametersCreateExaminationParameterDtoRequest.cs
> +        public float UpperLimit { get; set; }
Zdaje się, że float nie wymaga atrybutu [Required] - nie możemy i tak podać go pustego. Z automatu dostaniemy 0. Zamiast tego można wykorzystać poniższy atrybut:

[Range(0, float.MaxValue, ErrorMessage = "Please enter valid float Number")]

możemy zdefiniować maksymalne i minimalne wartości, które może przyjąć :)

2020-03-31 10:41 UTC, JJMPdsk commented on iPetCare/Application/Services/ExaminationParameterService.cs
> +            var examinationParameter = new ExaminationParameter()
Ta sama uwaga co @blc132 . To proste mapowanie, możemy spokojnie użyć mappera. Imo ręczne mapowanie jest usprawiedliwione w przypadkach gdy trzeba by było definiować customowe, skomoplikowane mapowanie :)

2020-03-31 10:41 UTC, JJMPdsk commented on iPetCare/Application/Services/ExaminationParameterService.cs
> +                : new ServiceResponse<ExaminationParametersCreateExaminationParameterDtoResponse>(HttpStatusCode.BadRequest);
Dodałbym info o tym dlaczego bad request. Sam bad request może niewiele mówić. Zwróciłbym może jakąś wiadomość typu "błąd podczas zapisu" czy coś w ten deseń

2020-03-31 10:41 UTC, JJMPdsk commented on iPetCare/Application/Services/ExaminationParameterService.cs
> +            if (examinationParameter == null)
Dobra robota!

2020-03-31 10:41 UTC, JJMPdsk commented on iPetCare/Application/Services/ExaminationParameterService.cs
> +            var examinationType = Context.ExaminationTypes.Find(dto.ExaminationTypeId);
Niżej korzystasz z FindAsync, lecz tutaj z Find w wersji synchronicznej. Czemu?

2020-03-31 10:41 UTC, JJMPdsk commented on iPetCare/Application/Services/ExaminationParameterService.cs
> +            var examinationType = Context.ExaminationTypes.Find(examinationParameter.ExaminationTypeId);
Czemu find zamiast findasync?

2020-03-31 10:41 UTC, JJMPdsk commented on iPetCare/Application/Services/ExaminationParameterService.cs
> +            return new ServiceResponse<ExaminationParametersUpdateExaminationParameterDtoResponse>(HttpStatusCode.BadRequest);
Nie będę pisał wszędzie, ale moze powinniśmy zwracać err message w takim przypadku?

2020-03-31 10:41 UTC, JJMPdsk commented on iPetCare/Application/Services/ExaminationParameterService.cs
> +            var examinationParameter = Context.ExaminationParameters.Find(examinationParameterId);
FindAsync

2020-03-31 10:41 UTC, JJMPdsk commented on iPetCare/Application/Services/ExaminationTypeService.cs
> +            var species = Context.Species.Find(dto.SpeciesId);
async

2020-03-31 16:04 UTC, kobrynsky submitted a review, later dismissed

2020-03-31 16:27 UTC, kobrynsky approved these changes

2020-03-31 16:27 UTC, merged